#!/usr/bin/env bash
#
# Ensure the required dep programs are available
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: January 30, 2026
# License: MIT
#
# Contributors: zenobit <zen@duck.com>

code=0

check() {
	echo -n "$*... "
	if ! "$@"; then
		echo 'error'
		code=1
	fi
}

check command -v bash
check command -v curl
check command -v jq

exit "$code"
