#!/usr/bin/env bash
#shellcheck disable=SC2089
#
# Make contrib.html file
#
# Author: zenobit <zen@duck.com>
# Date: February 03, 2026
# License: MIT
#

echo "Creating contrib.html"

file=contrib

title='contributing | osowoso.org'

id='	<div id="socials">
				<div id="socials">
					<a href="https://codeberg.org/oSoWoSo">Codeberg</a> |
					<a href="https://github.com/oSoWoSo">GitHub</a> |
					<a href="https://gitlab.com/osowoso">GitLab</a> |
					<a href="https://git.disroot.org/oSoWoSo">Disroot</a>
				</div>
					<!--
					<a href="https://osowoso.org/sh">SourceHut</a> |
					-->
					<!--
					<a href="https://osowoso.org/or">or</a> |
					-->
				<div id="git">
					<a href="https://smp10.simplex.im/g#rg4Sryn9kAgLt5I4u9SdL4b34MQgR141e7y1LiOV7sI">SimpleX</a> |
					<a href="https://youtube.com/@oSoWoSo.">YouTube</a> |
					<a href="https://patreon.com/oSoWoSo">Patreon</a>
					<!--
					<a href="https://osowoso.org/merch">Merch</a>
					-->
					<!--
					<a href=""></a>
					-->
				</div>
			</div>'

h='	<li><a href="/">home</a></li>
					<li><a href="/projects">projects</a></li>
					<li><a href="/contributing" class="active">contributing</a></li>
					<li><a href="/void">void</a></li>
					<li><a href="/resources">resources</a></li>
					<li><a href="/episodes">episodes</a></li>
					<li class="right"><a href="/contact""active">contact</a></li>'

top='	<h1 class="title">&gt; contributing</h1>
			<!--<img
				src="https://secure.gravatar.com/avatar/abfe8049a00a6dadca4c4c7b5bf19ed833d33393e42ed9501979201488c12494?s=128" class="logo self-portrait" alt="ysap" width="128" />-->'

body='		Contributed to projects.
				<br><br>
				<ul>
					<li>- <a href="https://github.com/void-linux/void-packages">void-packages</a> - The Void source packages collection</li>
					<li>- <a href="https://codeberg.org/mobinmob/abyss-packages">abyss-packages</a> - Unofficial repo of extra (packaging) templates for voidlinux</li>
					<li>- <a href="https://codeberg.org/mobinmob/xut">xut</a> - xtra user templates - Build and install packages for Void Linux, using templates from the abyss-packages unofficial repo</li>
					<li>- <a href="https://github.com/lucky7xz/drako">drako</a> - Grid-based, customizable and extendable TUI-Deck launcher </li>
					<li>- <a href="https://github.com/tvrzna/emptty">emptty</a> - Dead simple CLI Display Manager on TTY</li>
					<li>- <a href="https://github.com/quickemu-project/quickemu">quickemu</a> - Quickly create and run optimised Windows, macOS and Linux desktop virtual machines</li>
					<!--
					<li>- <a href=""></a> - </li>
					-->
				</ul>
				<br><br>

				<h2 class="title">Merged PRs</h2><br>
				Merged pull requests
				<br><br>
				<ul>
					<li>- <a href="https://github.com/void-linux/void-packages/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Azen0bit+is%3Amerged">PRs</a> - In <code class="highlight">void-packages</code></li>
					<li>- <a href="https://codeberg.org/mobinmob/abyss-packages/pulls?q=&type=all&sort=relevance&state=closed&labels=&milestone=0&project=0&assignee=0&poster=29282&archived=false">PRs</a> - In <code class="highlight">abyss-packages</code></li>
					<li>- <a href="https://github.com/quickemu-project/quickemu/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Azen0bit+is%3Amerged">PRs</a> - In <code class="highlight">quickemu</code></li>
					<li>- <a href="https://github.com/ivan-hc/AM/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Amerged+author%3Azen0bit">PRs</a> - In <code class="highlight">AM</code></li>
					<li>- <a href="https://github.com/ivan-hc/amcheck/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Amerged+author%3Azen0bit">PRs</a> - In  <code class="highlight">amcheck</code></li>
					<li>- <a href="https://github.com/slcw/SimpleX-Themes/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Amerged+author%3Azen0bit">PRs</a> - In <code class="highlight">SimpleX-Themes</code></li>
					<li>- <a href="https://github.com/cfgnunes/nautilus-scripts/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Amerged+author%3Azen0bit">PRs</a> - In <code class="highlight">nautilus-scripts</code></li>
					<!--
					<li>- <a href=""></a> - </li>
					<li>- <a href=""></a> - In <code class="highlights"></code></li>
					-->
					<li>- <a href="https://github.com/BashGui/easybashgui/pull/36">easybashgui</a> - another action for releases</li>
					<li>- <a href="https://github.com/tvrzna/emptty/pull/148">emptty</a> - Add IndentSelection</li>
					<li>- <a href="https://github.com/InterstellarDragonDev/Godot-Pie/pull/2">Godot-Pie</a> - Simple Pie Menu made in godot</li>
					<li>- <a href="https://github.com/labwc/labwc-menu-generator/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aclosed+author%3Azen0bit">labwc-menu-generator</a> - Add repology badge to readme</li>
					<li>- <a href="https://github.com/quickemu-project/quickemu-icons/pull/51">quickemu-icons</a> - Add void.svg</li>
					<li>- <a href="https://github.com/text-forge/text-forge/pull/152">text-forge</a> - Add GitHub Actions workflow for automated releases</li>
				</ul>
				<br><br>

				<h2 class="title">Waiting PRs</h2><br>
				Not yet merged pull requests
				<br><br>
				<ul>
					<li>- <a href="https://github.com/lucky7xz/drako/pull/3">drako</a> - change row numbers to 1-9</li>
					<li>- <a href="https://github.com/void-linux/void-packages/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aopen+author%3Azen0bit">PRs</a> - In <code class="highlight">void-packages</code></li>
					<!--
					<li>- <a href=""></a> - In <code class="highlights"></code></li>
					-->
				</ul>
				<br><br>

				<h2 class="title">Translations</h2><br>
				Improving translations in this projects.
				<br><br>
				<ul>
					<li>- <a href="https://github.com/Alovoa/alovoa">Alovoa</a> - Free and open-source dating platform that respects your privacy</li>
					<li>- <a href="https://github.com/kando-menu/kando">Kando</a> - Do things with utmost efficiency</li>
					<li>- <a href="https://github.com/ImranR98/Obtainium">Obtainium</a> - Get Android app updates straight from the source</li>
					<li>- <a href="https://github.com/simplex-chat/simplex-chat">SimpleX Chat</a> - First messaging network operating without user identifiers of any kind - 100% private by design!</li>
					<!--
					<li>- <a href=""></a> - </li>
					-->
					<li>'

footer='			<pre class="footer"><code>
source: <a class="alt" href="https://github.com/oSoWoSo/osowoso">github.com/oSoWoSo/osowoso</a>
&copy; zenobit - oSoWoSo <script>document.write(new Date().getFullYear())</script>
			</code></pre>
		</div>
	</body>
</html>'

# shellcheck disable=SC2090
giscus=$(
	GISCUS_REPO="${GISCUS_REPO:-osowoso/osowoso}"
	GISCUS_REPO_ID="${GISCUS_REPO_ID:-R_kgDOPwu1wg}"
	GISCUS_CATEGORY_ID="${GISCUS_CATEGORY_ID:-DIC_kwDOPwu1ws4C1qTI}"
	GISCUS_MAPPING="${GISCUS_MAPPING:-pathname}"
	GISCUS_THEME="${GISCUS_THEME:-noborder_dark}"
	GISCUS_LANG="${GISCUS_LANG:-en}"
	cat << EOF
			<!-- GitHub Discussions Widget -->
			<div class="discussions-container" style="margin: 2em 0 1em 0; padding: 1em 0; border-top: 1px solid #444;">
				<script src="https://giscus.app/client.js"
					data-repo="$GISCUS_REPO"
					data-repo-id="$GISCUS_REPO_ID"
					data-category-id="$GISCUS_CATEGORY_ID"
					data-mapping="$GISCUS_MAPPING"
					data-strict="0"
					data-reactions-enabled="1"
					data-emit-metadata="0"
					data-input-position="bottom"
					data-theme="$GISCUS_THEME"
					data-lang="$GISCUS_LANG"
					data-loading="lazy"
					crossorigin="anonymous"
					async>
				</script>
			</div>
			<!-- End GitHub Discussions Widget -->
EOF
)

export title h top body giscus footer

cat << EOF> "static/${file}.html"
<!doctype html>
<html>
	<head>
		<title>${title}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<link rel="icon" href="/static/favicon.jpg">

		<link rel="stylesheet" href="/static/style.css?v=3">
		<link rel="stylesheet" href="/static/ansi.css?v=2">

		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Fira+Mono:wght@400;500;700&display=swap" rel="stylesheet">
	</head>
	<body>
		<div id="container">
			<div id="top-nav">
				<ul>
				${h}
				</ul>
			</div>

		${top}
			<p class="content">
		${body}
			</p>
		${id}
${giscus}
${footer}
EOF

unset title h top body footer
