#!/usr/bin/env bash
#
# Make a page for each video by copying the static video page
#
# Can we use symlinks instead? for now just copy them because they are small
# files.
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: January 30, 2026
# License: MIT
#
# Contributors: zenobit <zen@duck.com>

num_re='^[0-9]+$'
i=0
while IFS=$'\t' read -r num _; do
	# sanity
	[[ $num =~ $num_re ]] || exit
	mkdir -p "_site/y/$num"
	cat _site/y.html > "_site/y/$num/index.html"
	((i++))
done < <(./make-list)
echo "$i videos"
