#!/usr/bin/env bash
#
# Make the news section
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: December 06, 2025
# License: MIT

. ./theme || exit

{
echo -n "New Work In Progress website"
} | ./tools/box -hp 1 -vp 1 -tc "$COLOR5" -t 'News' -bc "$COLOR4" -T plain
