#!/usr/bin/env bash
#
# Print the git hostings - indended to be passed to `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: January 30, 2026
# License: MIT
#
# Contributors: zenobit <zen@duck.com>

. ./theme || exit

readarray -t GIT << "EOF"
Codeberg|https://codeberg.org/oSoWoSo
GitHub|https://github.com/oSoWoSo
GitLab|https://gitlab.com/osowoso
Disroot|https://git.disroot.org/oSoWoSo
EOF

UNDERLINE=$'\x1b[3m'

for line in "${GIT[@]}"; do
	IFS='|' read -r name url <<< "$line"

	echo -n "$COLOR2$name$RST"
	echo -n '|'
	echo -n "$UNDERLINE$COLOR2$url$RST"
	echo
done
