#!/usr/bin/env bash
#
# Generate the page as seen by `curl osowoso.org/help`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: January 30, 2026
# License: MIT
#
# Contributors: zenobit <zen@duck.com>

. ./theme || exit

{

# create the header
./make-header -p 7 |
    ./tools/box -hp 4 -T plain

echo

# create the legend
./make-legend -f

} | ./tools/lpad '  ' | ./tools/rtrim-ansi-aware
