#!/usr/bin/env bash
#
# Print the "about" message formatted how I like it - this output is intended to
# be piped into `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: January 30, 2026
# License: MIT
#
# Contributors: zenobit <zen@duck.com>

. ./theme || exit 1

readarray -t ABOUT << "EOF"
Yo what's up everyone my name's
zenobit from open Source World Society.
Use this site to easily find our content!
EOF

for line in "${ABOUT[@]}"; do
	echo "$COLOR1$line$RST"
done
