#!/usr/bin/env bash
#
# Print the colorized YSAP logo and metadata used as the header for all pages
# you can request via `curl`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: January 30, 2026
# License: MIT
#
# Contributors: zenobit <zen@duck.com>

. ./theme || exit
. ./tools/repeat-char || exit

padding=1
while getopts 'p:' opt; do
	case "$opt" in
		p) padding=$OPTARG;;
		*) exit 1;;
	esac
done

padding=$(repeat-char ' ' "$padding")

mapfile -t logo < <(./make-logo)

description=(
	""
	"${COLOR5}open Source World Society$RST"
	"${COLOR5}Tools and guides by oSoWoSo$RST"
	"${COLOR1}https://osowoso.org$RST"
	''
	"${COLOR5}Source: ${COLOR1}https://github.com/oSoWoSo/.github$RST"
)

len=${#logo[@]}

for ((i = 0; i < len; i++)); do
	logo_line=${logo[i]}
	desc_line=${description[i]}

	echo "$logo_line$padding$desc_line"
done
