#!/usr/bin/env bash
#shellcheck disable=SC2089
#
# Make video.html file
#
# Author: zenobit <zen@duck.com>
# Date: February 03, 2026
# License: MIT
#

echo "Creating video.html"

file=video

title='video | osowoso.org'

id='<pre class="footer"><code>'

h='	<li><a href="/">home</a></li>
					<li><a href="/projects">projects</a></li>
					<li><a href="/contributing">contributing</a></li>
					<li><a href="/void">void</a></li>
					<li><a href="/resources">resources</a></li>
					<li><a href="/episodes">episodes</a></li>
					<li class="right"><a href="/contact">contact</a></li>'

top='<h1 class="title" id="video-title">[object Object]</h1>'

body='	<span id="video-description">nothing here yet bud</span>


				<br>
				<br>
				<iframe class="shadow" id="video-yt-frame" width="560" height="315"
								src="https://www.youtube.com/embed/KwRow9DdFJ0"
								title="" frameBorder="0"   allow="accelerometer;
								autoplay; clipboard-write; encrypted-media;
								gyroscope; picture-in-picture; web-share"
								allowFullScreen>
								</iframe>
								<br>
								<br>

								<div>
									<button onclick="goToPrevEpisode()" id="prev-episode-btn">
										&lt; Previous Episode
									</button>
									<button onclick="goToNextEpisode()" id="next-episode-btn">
										Next Episode &gt;
									</button>
								</div>

								<br>
								<br>
								<ul>
										<li>- <a id="video-youtube-link" href="#">Watch on YouTube</a></li>
										<li>- <a id="video-instagram-link" href="#">Watch on Instagram</a></li>
										<li>- <a id="video-tiktok-link" href="#">Watch on TikTok</a></li>
								</ul>'

footer=$(cat << EOF
source: <a class="alt" href="https://github.com/oSoWoSo/osowoso">github.com/oSoWoSo/osowoso</a>
&copy; zenobit - osowoso <script>document.write(new Date().getFullYear())</script>
			</code></pre>
		</div>
		<script src="/static/episodes.js"></script>
		<script>
			function isFirstEpisode(currentNum) {
				return currentNum === 1;
			}

			function isLastEpisode(currentNum) {
				return currentNum === EPISODES.episodes.length;
			}

			function getCurrentEpisodeNum() {
				// figure out what video we are based on the windows location
				const path = window.location.pathname
					.replace(/index\.html$/, '')
					.replace(/\/+$/, '');

				console.log('looking up %s', path);

				let m, num;
				if ((m = path.match(/^\/v\/([0-9]+)$/))) {
					num = m[1];
				} else {
					throw 'unrecoginzed url';
				}

				let episode = EPISODES.episodes[num - 1];
				if (!episode) {
					throw 'non existent episode';
				}

				return +num;
			}

			function goToNextEpisode() {
				let nextNum = getCurrentEpisodeNum() + 1;
				let nextEpisode = EPISODES.episodes[nextNum - 1];
				if (nextEpisode) {
					globalThis.location.href = '/v/' + nextNum;
				}
			}

			function goToPrevEpisode() {
				let prevNum = getCurrentEpisodeNum() - 1;
				let prevEpisode = EPISODES.episodes[prevNum - 1];
				if (prevEpisode) {
					globalThis.location.href = '/v/' + prevNum;
				}
			}

			const titleElem = document.getElementById('video-title');
			const descriptionElem = document.getElementById('video-description');
			const ytVideoElem = document.getElementById('video-yt-frame');

			const ytLinkElem = document.getElementById('video-youtube-link');
			const igLinkElem = document.getElementById('video-instagram-link');
			const ttLinkElem = document.getElementById('video-tiktok-link');

			const prevEpisodeBtn = document.getElementById('prev-episode-btn');
			const nextEpisodeBtn = document.getElementById('next-episode-btn');

			const num = getCurrentEpisodeNum();
			const episode = EPISODES.episodes[num - 1];

			// set title and description
			titleElem.textContent = num + '. ' + episode.title;
			descriptionElem.textContent = episode.desc;
			document.title = episode.title + ' | osowoso.org';

			// set youtube iframe
			let yt = episode.external.youtube;
			if ((m = yt.match(/v=(.*)$/))) {
				ytVideoElem.src = 'https://www.youtube.com/embed/' + m[1];
			} else {
				throw 'invalid youtube link: ' + yt;
			}

			// set external links
			ytLinkElem.href = episode.external.youtube;
			igLinkElem.href = episode.external.instagram;
			ttLinkElem.href = episode.external.tiktok;

			if (isFirstEpisode(episode.num)) {
				prevEpisodeBtn.disabled = true;
				prevEpisodeBtn.setAttribute('title', 'This is the first episode :)');
			}
			if (isLastEpisode(episode.num)) {
				nextEpisodeBtn.disabled = true;
				nextEpisodeBtn.setAttribute('title', 'You have made it to the end! :D' );
			}
		</script>
	</body>
</html>
EOF
)

# shellcheck disable=SC2090
giscus=$(
	GISCUS_REPO="${GISCUS_REPO:-osowoso/osowoso}"
	GISCUS_REPO_ID="${GISCUS_REPO_ID:-R_kgDOPwu1wg}"
	GISCUS_CATEGORY_ID="${GISCUS_CATEGORY_ID:-DIC_kwDOPwu1ws4C1qTI}"
	GISCUS_MAPPING="${GISCUS_MAPPING:-pathname}"
	GISCUS_THEME="${GISCUS_THEME:-noborder_dark}"
	GISCUS_LANG="${GISCUS_LANG:-en}"
	cat << EOF
			<!-- GitHub Discussions Widget -->
			<div class="discussions-container" style="margin: 2em 0 1em 0; padding: 1em 0; border-top: 1px solid #444;">
				<script src="https://giscus.app/client.js"
					data-repo="$GISCUS_REPO"
					data-repo-id="$GISCUS_REPO_ID"
					data-category-id="$GISCUS_CATEGORY_ID"
					data-mapping="$GISCUS_MAPPING"
					data-strict="0"
					data-reactions-enabled="1"
					data-emit-metadata="0"
					data-input-position="bottom"
					data-theme="$GISCUS_THEME"
					data-lang="$GISCUS_LANG"
					data-loading="lazy"
					crossorigin="anonymous"
					async>
				</script>
			</div>
			<!-- End GitHub Discussions Widget -->
EOF
)

export title h top body giscus footer

cat << EOF> "static/${file}.html"
<!doctype html>
<html>
	<head>
		<title>${title}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<link rel="icon" href="/static/favicon.jpg">

		<link rel="stylesheet" href="/static/style.css?v=3">
		<link rel="stylesheet" href="/static/ansi.css?v=2">

		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Fira+Mono:wght@400;500;700&display=swap" rel="stylesheet">
	</head>
	<body>
		<div id="container">
			<div id="top-nav">
				<ul>
				${h}
				</ul>
			</div>

			${top}
			<p class="content">
			${body}
			</p>
			${id}
${giscus}
${footer}
EOF

unset title h top body footer
