#!/usr/bin/env bash
#
# Generate the page as seen by `curl osowoso.org`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: January 30, 2026
# License: MIT
#
# Contributors: zenobit <zen@duck.com>

. ./theme || exit

{
./make-header -p 7 |
    ./tools/box -hp 4 -T plain

./make-news

./make-body

./make-legend

} | ./tools/lpad '  ' | ./tools/rtrim-ansi-aware
