#!/usr/bin/env bash
#
# Print the "about" message formatted how I like it - this output is intended to
# be piped into `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: January 30, 2026
# License: MIT
#
# Contributors: zenobit <zen@duck.com>

. ./theme || exit 1

readarray -t ABOUT << "EOF"
Don't buy a pig in a poke
Don't use proprietary Operating System or software

Use Open Source
Like Linux kernel
Used in best open source OS's on planet Earth
Join us...

Our world is in our hands...
EOF

for line in "${ABOUT[@]}"; do
	echo "$COLOR1$line$RST"
done
