#!/usr/bin/env bash
#
# Print the socials - indended to be passed to `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: January 30, 2026
# License: MIT
#
# Contributors: zenobit <zen@duck.com>

. ./theme || exit

readarray -t SOCIALS << "EOF"
YouTube|https://osowoso.org/youtube
Patreon|https://osowoso.org/patreon
SimpleX|https://osowoso.org/simplex
EOF

UNDERLINE=$'\x1b[3m'

for line in "${SOCIALS[@]}"; do
	IFS='|' read -r name url <<< "$line"

	echo -n "$COLOR2$name$RST"
	echo -n '|'
	echo -n "$UNDERLINE$COLOR2$url$RST"
	echo
done
