#!/usr/bin/env bash
#
# Print the oSoWoSo logo
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: January 30, 2026
# License: MIT
#
# # Contributors
# - Dave Eddy <ysap@daveeddy.com>
# - Joshua Rayton <joshua.rayton@gmail.com>
# - zenobit <zen@duck.com>

. ./theme || exit

COLOR6=$'\e[48;5;223m'          # off-white (background)
COLOR7=$'\e[38;5;160m'          # red
COLOR8=$'\e[38;5;214;48;5;202m' # yellow (text) orange (background)

readarray -t LOGO << EOF
       AAAA        A       A       AAAA
  AA  CC  BB   AA  CC  A  CC  AA  CC  BB   AA
 C  C  BBBBCA C  C  BCCBCCB  C  C  BBBBCA C  C
 BAAB BCAAACB BAAB   BC CB   BAAB BCAAACB BAAB
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EOF

shopt -s extglob

for line in "${LOGO[@]}"; do
	line=${line//+(A|B)/$COLOR5&$RST}
	line=${line//+(C)/$COLOR6&$RST}
	line=${line//+(D)/$COLOR7&$RST}
	line=${line//+(E)/$COLOR8&$RST}

	line=${line//[ADE]/▄}
	line=${line//B/▀}
	line=${line//C/ }

	echo "$line"
done

