#!/usr/bin/env bash
#shellcheck disable=SC2089
#
# Make html files
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: January 30, 2026
# License: MIT
#
# Contributors: zenobit <zen@duck.com>

#TODO: Add episodes.html

for f in index contact contrib projects resources video void; do
	echo "Creating $f.html"
	file="${f}"

# Differences
	if [ "$file" = episodes ]; then
		id='<br>

			<table id="episodes-table" class="shadow">
				<thead>
					<tr>
						<th>TITLE</th>
						<th>DESCRIPTION</th>
						<th>LINK</th>
					</tr>
				</thead>
				<tbody id="episodes-tbody">
				</tbody>
			</table>
'
	elif [ "$file" = video ]; then
		id='<pre class="footer"><code>'
	else
		id='<div id="socials">
				<a href="https://osowoso.org/codeberg">Codeberg</a> |
				<a href="https://osowoso.org/github">GitHub</a> |
				<a href="https://osowoso.org/sh">SourceHut</a> |
				<a href="https://osowoso.org/or">or</a> |
				<a href="https://osowoso.org/gitlab">GitLab</a> |
				<a href="https://osowoso.org/disroot">Disroot</a> |
				<a href="https://osowoso.org/simplex">SimpleX</a> |
				<a href="https://osowoso.org/youtube">YouTube</a> |
				<a href="https://osowoso.org/patreon">Patreon</a> |
				<a href="https://osowoso.org/merch">Merch</a>
			</div>'
	fi

	if [ "$file" = contact ]; then
		title='contact | osowoso.org'
		h='	<li><a href="/">home</a></li>
					<li><a href="/episodes">episodes</a></li>
					<li><a href="/resources">resources</a></li>
					<li><a href="/void">void</a></li>
					<li class="right"><a href="/contact" class="active">contact</a></li>'
		top='<h1 class="title">&gt; contact</h1>
			<img src="https://secure.gravatar.com/avatar/6c7581ac69deeb96d3e9d0ee1e941af3?s=128" class="logo self-portrait" alt="ysap" width="128" />'
		body='	You can follow me on my socials below and join the discord to chat with the community.
				<br>
				<br>
				If you want to contact me directly please use the following email.
				<br>
				<br>
				<a href="mailto:zen@duck.com">zen@duck.com</a>
				<br>
				<br>
				If you are looking for my technical blog or music I have written you can check out my personal website here.
				<br>
				<br>
				<a href="https://osowoso.org">oSoWoSo.org</a>'
		footer='			<pre class="footer"><code>
source: <a class="alt" href="https://github.com/oSoWoSo/osowoso">github.com/oSoWoSo/osowoso</a>
&copy; zenobit - oSoWoSo <script>document.write(new Date().getFullYear())</script>
			</code></pre>
		</div>
	</body>
</html>'
	fi

	if [ "$file" = contrib ]; then
		title='contributing | osowoso.org'
		h='	<li><a href="/">home</a></li>
					<li><a href="/episodes">episodes</a></li>
					<li><a href="/resources">resources</a></li>
					<li><a href="/projects">projects</a></li>
					<li><a href="/contributing" class="active">contributing</a></li>
					<li><a href="/void">void</a></li>
					<li class="right"><a href="/contact""active">contact</a></li>'
		top='<h1 class="title">&gt; contributing</h1>
			<!--<img
				src="https://secure.gravatar.com/avatar/6c7581ac69deeb96d3e9d0ee1e941af3?s=128" class="logo self-portrait" alt="ysap" width="128" />-->'
		body='	Contributing to projects.
				<br><br>
				<ul>
					<!--<li>- <a href="https://github.com/"></a> - </li>-->
					<li>- <a href="https://github.com/void-linux/void-packages">void-packages</a> - The Void source packages collection</li>
					<li>- <a href="https://codeberg.org/mobinmob/xut">xut</a> - xtra user templates - Build and install packages for Void Linux, using templates from the abyss-packages unofficial repo</li>
					<li>- <a href="https://codeberg.org/mobinmob/abyss-packages">abyss-packages</a> - Unofficial repo of extra (packaging) templates for voidlinux</li>
					<li>- <a href="https://github.com/lucky7xz/drako">drako</a> - Grid-based, customizable and extendable TUI-Deck launcher </li>
					<li>- <a href="https://github.com/tvrzna/emptty">emptty</a> - Dead simple CLI Display Manager on TTY</li>
					<li>- <a href="https://github.com/quickemu-project/quickemu">quickemu</a> - Quickly create and run optimised Windows, macOS and Linux desktop virtual machines</li>
				</ul>
				<br><br>

				<h2 class="title">Merged PRs</h2><br>
				Merged pull requests
				<br><br>
				<ul>
					<li>- <a href="https://github.com/void-linux/void-packages/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Azen0bit+is%3Amerged">PRs</a> - In <code class="highlight">void-packages</code></li>
					<li>- <a href="https://codeberg.org/mobinmob/abyss-packages/pulls?q=&type=all&sort=relevance&state=closed&labels=&milestone=0&project=0&assignee=0&poster=29282&archived=false">PRs</a> - In <code class="highlight">abyss-packages</code></li>
					<li>- <a href="https://github.com/quickemu-project/quickemu/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Azen0bit+is%3Amerged">PRs</a> - In <code class="highlight">quickemu</code></li>
					<!--<li>- <a href="https://github.com//pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Azen0bit+is%3Amerged">PRs</a> - In <code class="highlight"></code></li>-->
					<li>- <a href="https://github.com/ivan-hc/AM/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Amerged+author%3Azen0bit">PRs</a> - In <code class="highlight">AM</code></li>
					<li>- <a href="https://github.com/tvrzna/emptty/pull/148">emptty</a> - Add IndentSelection</li>
				</ul>
				<br><br>

				<h2 class="title">Waiting PRs</h2><br>
				Not yet merged pull requests
				<br><br>
				<ul>
					<li>- <a href="https://github.com/void-linux/void-packages/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aopen+author%3Azen0bit">PRs</a> - In <code class="highlight">void-packages</code></li>
					<!--<li>- <a href="https://github.com//pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aopen+author%3Azen0bit">PRs</a> - In <code class="highlight"></code></li>-->
					<li>- <a href="https://github.com/lucky7xz/drako/pull/3">drako</a> - change row numbers to 1-9</li>
				</ul>
				<br><br>

				<h2 class="title">Translations</h2><br>
				Improving translations in this projects.
				<br><br>
				<ul>
					<li>- <a href="https://github.com/simplex-chat/simplex-chat">SimpleX Chat</a> - First messaging network operating without user identifiers of any kind - 100% private by design!</li>
					<li>- <a href="https://github.com/ImranR98/Obtainium">Obtainium</a> - Get Android app updates straight from the source</li>
					<li>- <a href="https://github.com/kando-menu/kando">Kando</a> - Do things with utmost efficiency</li>
					<!--<li>- <a href="https://github.com/"></a> - </li>-->
					<li>'
		footer='			<pre class="footer"><code>
source: <a class="alt" href="https://github.com/oSoWoSo/osowoso">github.com/oSoWoSo/osowoso</a>
&copy; zenobit - oSoWoSo <script>document.write(new Date().getFullYear())</script>
			</code></pre>
		</div>
	</body>
</html>'
	fi

	if [ "$file" = episodes ]; then
		title='episodes | osowoso.org'
		h='	<li><a href="/">home</a></li>
					<li><a href="/episodes">episodes</a></li>
					<li><a href="/resources">resources</a></li>
					<li><a href="/projects">projects</a></li>
					<li><a href="/contributing">contributing</a></li>
					<li><a href="/void">void</a></li>
					<li class="right"><a href="/contact">contact</a></li>'
		top='<h1 class="title">&gt; episodes</h1>
			<img src="/static/osowoso.png" class="logo hide-mobile" alt="osowoso" height="75" />'
		body='	<span class="highlight">You Suck at
					Programming</span> is the series that
				kickstarted my content creation journey!<br><br>

				This series
				features 2-5 minute videos that cover cool
				Unix/Bash facts or gotchas, offering insights
				that are either useful or, at the very least,
					  interesting.
				<br>
				<br>
				There is also a compilation of the first 50
				episodes <a
				href="https://www.youtube.com/watch?v=KwRow9DdFJ0">available
				on YouTube</a>.
				<br>
				<br>
				<span class="highlight">$ curl</span> osowoso.org/episodes
				<br>'
		footer=$(cat <<EOF
<pre class="footer"><code>
source: <a class="alt" href="https://github.com/oSoWoSo/osowoso">github.com/oSoWoSo/osowoso</a>
&copy; zenobit - oSoWoSo <script>document.write(new Date().getFullYear())</script>
			</code></pre>
		</div>
		<script src="/static/episodes.js"></script>
		<script>
			var tbody = document.getElementById('episodes-tbody');
			const episodeCount = EPISODES.episodes.length;

			EPISODES.episodes.forEach(function (episode) {
				let num = episode.num;

				let numFormatted = num.toString();
				for (let i = numFormatted.length; i < episodeCount.toString().length; i++) {
					numFormatted = '0' + numFormatted;
				}

				let tr = document.createElement('tr');
				let td, span;

				td = document.createElement('td');
				span = document.createElement('span');
				span.classList.add('number');
				span.innerHTML = numFormatted + '. ';
				td.appendChild(span);
				span = document.createElement('span');
				span.classList.add('name');
				span.textContent = episode.title;
				td.appendChild(span);
				td.classList.add('title');
				tr.appendChild(td);

				td = document.createElement('td');
				let i = 0;
				let s = '';
				episode.desc.split('').forEach(function (c) {
					switch (c) {
						case '&': c = '&amp;'; break;
						case '<': c = '&lt;'; break;
						case '>': c = '&gt;'; break;
						case '"': c = '&quot;'; break;
						case "'": c = '&#39;'; break;
						case '/': c = '&#47;'; break;
EOF
)
	fi

	if [ "$file" = index ]; then
		title=osowoso.org
		h='	<li><a href="/" class="active">home</a></li>
					<li><a href="/episodes">episodes</a></li>
					<li><a href="/resources">resources</a></li>
					<li><a href="/projects">projects</a></li>
					<li><a href="/contributing">contributing</a></li>
					<li><a href="/void">void</a></li>
					<li class="right"><a href="/contact">contact</a></li>'
		top='<h1 class="title">&gt; osowoso.org</h1>
			<img src="https://secure.gravatar.com/avatar/abfe8049a00a6dadca4c4c7b5bf19ed833d33393e42ed9501979201488c12494?s=128" class="logo self-portrait" alt="osowoso" width="128" />'
		body=$(cat << EOF
	Yo what's up everyone my name's zenobit from open Source World Society!
				<br>
				<br>
				This is the site for our projects <span class="highlight">oSoWoSo</span> where We
				try to make world more open source.
				<br>
				<br>
				** The <span class="highlight"><i>Complete
				Bash Course</i></span> is now live! ** It's available as
				a 7+ hour YouTube video for free here: <a
				href="htps://course.ysap.sh">course.ysap.sh</a>.
				<br>
EOF
)
		footer='			<pre class="terminal shadow" id="main-terminal"><code></code></pre>
			<pre class="footer"><code>
source: <a class="alt" href="https://github.com/oSoWoSo/osowoso">github.com/oSoWoSo/osowoso</a>
&copy; zenobit - oSoWoSo <script>document.write(new Date().getFullYear())</script>
			</code></pre>
		</div>
		<script src="/static/commands.js"></script>
		<script src="/static/terminal.js"></script>
	</body>
</html>'
	fi

	if [ "$file" = projects ]; then
		title='projects | osowoso.org'
		h='	<li><a href="/">home</a></li>
					<li><a href="/episodes">episodes</a></li>
					<li><a href="/resources">resources</a></li>
					<li><a href="/projects" class="active">projects</a></li>
					<li><a href="/contributing">contributing</a></li>
					<li><a href="/void">void</a></li>
					<li class="right"><a href="/contact""active">contact</a></li>'
		top='<h1 class="title">&gt; projects</h1>
			<!--<img
				src="https://secure.gravatar.com/avatar/6c7581ac69deeb96d3e9d0ee1e941af3?s=128" class="logo self-portrait" alt="ysap" width="128" />-->'
		body='	A collection of projects and tools that Ive created that you all may find useful.
				<br><br>
				<ul>
					<li>- <a href="https://course.osowoso.org">The Complete Bash Course</a> - The official YSAP Bash course</li>
					<li>- <a href="https://style.osowoso.org">Bash Style Guide</a> - The official YSAP style guide</li>
				</ul>
				<br><br>

				<h2 class="title">Utilities</h2><br>
				Various utilities Ive created center around bash or programming in general.
				<br><br>
				<ul>
					<li>- <a href="https://github.com/bahamas10/bash-vardump">bash-vardump</a> - A <code class="highlight">vardump</code> function for bash</li>
					<li>- <a href="https://github.com/bahamas10/bash-stacktrace">bash-stacktrace</a> - A <code class="highlight">stacktrace</code> function for bash</li>
					<li>- <a href="https://github.com/bahamas10/sshp">sshp</a> - A parallel ssh executor in C</li>
				</ul>
				<br><br>

				<h2 class="title">Fun Extras</h2><br>
				Some less-useful but fun creations that Ive made and talked about in various videos.
				<br><br>
				<ul>
					<li>- <a href="https://bahamas10.github.io/ryb/">RYB Color Picker</a> - An RYB HTML Color Picker</li>
					<li>- <a href="https://xmas.osowoso.org">X-Mas Tree Animation</a> - Terminal animation made for Christmas in Bash</li>
					<li>- <a href="https://undercurrents.osowoso.org">Undercurrents</a> - A particle animation written in C using SDL2</li>
					<li>- <a href="https://nightfall.osowoso.org">Nightfall</a> - A music player TUI written in Bash</li>
				</ul>'
		footer='			<pre class="footer"><code>
source: <a class="alt" href="https://github.com/oSoWoSo/osowoso">github.com/oSoWoSo/osowoso</a>
&copy; zenobit - oSoWoSo <script>document.write(new Date().getFullYear())</script>
			</code></pre>
		</div>
	</body>
</html>'
	fi

	if [ "$file" = resources ]; then
		title='resources | osowoso.org'
		h='	<li><a href="/">home</a></li>
					<li><a href="/episodes">episodes</a></li>
					<li><a href="/resources" class="active">resources</a></li>
					<li><a href="/projects">projects</a></li>
					<li><a href="/contributing">contributing</a></li>
					<li><a href="/void">void</a></li>
					<li class="right"><a href="/contact""active">contact</a></li>'
		top='<h1 class="title">&gt; resources</h1>
			<!--<img
				src="https://secure.gravatar.com/avatar/6c7581ac69deeb96d3e9d0ee1e941af3?s=128" class="logo self-portrait" alt="ysap" width="128" />-->'
		body='	Excellent open source software We cannot live without.
				<br><br>
				<ul>
					<li>- <a href="https://www.kernel.org/">Linux kernel</a> - Linux is a clone of the operating system Unix, written from scratch by Linus Torvalds with assistance from a loosely-knit team of hackers across the Net. It aims towards POSIX and Single UNIX Specification compliance.</li>
					<li>- <a href="https://voidlinux.org">Void Linux</a> - Void is a general purpose operating system, based on the monolithic Linux kernel. Its package system allows you to quickly install, update and remove software; software is provided in binary packages or can be built directly from sources with the help of the XBPS source packages collection.</li>
					<!--<li>- <a href=""></a> - </li>-->
				</ul>
				<br><br>

				<h2 class="title">Utilities</h2><br>
				Various utilities created center around bash or programming in general.
				<br><br>
				<ul>
					<li>- <a href="https://github.com/bahamas10/bash-vardump">bash-vardump</a> - A <code class="highlight">vardump</code> function for bash</li>
					<li>- <a href="https://github.com/bahamas10/bash-stacktrace">bash-stacktrace</a> - A <code class="highlight">stacktrace</code> function for bash</li>
					<li>- <a href="https://github.com/bahamas10/sshp">sshp</a> - A parallel ssh executor in C</li>
				</ul>
				<br><br>

				<h2 class="title">Fun Extras</h2><br>
				Some less-useful but fun creations that I made and talked about in various videos.
				<br><br>
				<ul>
					<li>- <a href="https://bahamas10.github.io/ryb/">RYB Color Picker</a> - An RYB HTML Color Picker</li>
					<li>- <a href="https://xmas.osowoso.org">X-Mas Tree Animation</a> - Terminal animation made for Christmas in Bash</li>
					<li>- <a href="https://undercurrents.osowoso.org">Undercurrents</a> - A particle animation written in C using SDL2</li>
					<li>- <a href="https://nightfall.osowoso.org">Nightfall</a> - A music player TUI written in Bash</li>
				</ul>'
		footer='			<pre class="footer"><code>
source: <a class="alt" href="https://github.com/oSoWoSo/osowoso">github.com/oSoWoSo/osowoso</a>
&copy; zenobit - oSoWoSo <script>document.write(new Date().getFullYear())</script>
			</code></pre>
		</div>
	</body>
</html>'
	fi

	if [ "$file" = video ]; then
		title='video | osowoso.org'
		h='	<li><a href="/">home</a></li>
					<li><a href="/episodes">episodes</a></li>
					<li><a href="/resources">resources</a></li>
					<li><a href="/projects">projects</a></li>
					<li><a href="/contributing">contributing</a></li>
					<li><a href="/void">void</a></li>
					<li class="right"><a href="/contact">contact</a></li>'
		top='<h1 class="title" id="video-title">[object Object]</h1>'
		body='	<span id="video-description">nothing here yet bud</span>


				<br>
				<br>
				<iframe class="shadow" id="video-yt-frame" width="560" height="315"
								src="https://www.youtube.com/embed/KwRow9DdFJ0"
								title="" frameBorder="0"   allow="accelerometer;
								autoplay; clipboard-write; encrypted-media;
								gyroscope; picture-in-picture; web-share"
								allowFullScreen>
								</iframe>
								<br>
								<br>

								<div>
									<button onclick="goToPrevEpisode()" id="prev-episode-btn">
										&lt; Previous Episode
									</button>
									<button onclick="goToNextEpisode()" id="next-episode-btn">
										Next Episode &gt;
									</button>
								</div>

								<br>
								<br>
								<ul>
										<li>- <a id="video-youtube-link" href="#">Watch on YouTube</a></li>
										<li>- <a id="video-instagram-link" href="#">Watch on Instagram</a></li>
										<li>- <a id="video-tiktok-link" href="#">Watch on TikTok</a></li>
								</ul>'
		footer=$(cat << EOF
source: <a class="alt" href="https://github.com/oSoWoSo/osowoso">github.com/oSoWoSo/osowoso</a>
&copy; zenobit - osowoso <script>document.write(new Date().getFullYear())</script>
			</code></pre>
		</div>
		<script src="/static/episodes.js"></script>
		<script>
			function isFirstEpisode(currentNum) {
				return currentNum === 1;
			}

			function isLastEpisode(currentNum) {
				return currentNum === EPISODES.episodes.length;
			}

			function getCurrentEpisodeNum() {
				// figure out what video we are based on the windows location
				const path = window.location.pathname
					.replace(/index\.html$/, '')
					.replace(/\/+$/, '');

				console.log('looking up %s', path);

				let m, num;
				if ((m = path.match(/^\/v\/([0-9]+)$/))) {
					num = m[1];
				} else {
					throw 'unrecoginzed url';
				}

				let episode = EPISODES.episodes[num - 1];
				if (!episode) {
					throw 'non existent episode';
				}

				return +num;
			}

			function goToNextEpisode() {
				let nextNum = getCurrentEpisodeNum() + 1;
				let nextEpisode = EPISODES.episodes[nextNum - 1];
				if (nextEpisode) {
					globalThis.location.href = '/v/' + nextNum;
				}
			}

			function goToPrevEpisode() {
				let prevNum = getCurrentEpisodeNum() - 1;
				let prevEpisode = EPISODES.episodes[prevNum - 1];
				if (prevEpisode) {
					globalThis.location.href = '/v/' + prevNum;
				}
			}

			const titleElem = document.getElementById('video-title');
			const descriptionElem = document.getElementById('video-description');
			const ytVideoElem = document.getElementById('video-yt-frame');

			const ytLinkElem = document.getElementById('video-youtube-link');
			const igLinkElem = document.getElementById('video-instagram-link');
			const ttLinkElem = document.getElementById('video-tiktok-link');

			const prevEpisodeBtn = document.getElementById('prev-episode-btn');
			const nextEpisodeBtn = document.getElementById('next-episode-btn');

			const num = getCurrentEpisodeNum();
			const episode = EPISODES.episodes[num - 1];

			// set title and description
			titleElem.textContent = num + '. ' + episode.title;
			descriptionElem.textContent = episode.desc;
			document.title = episode.title + ' | osowoso.org';

			// set youtube iframe
			let yt = episode.external.youtube;
			if ((m = yt.match(/v=(.*)$/))) {
				ytVideoElem.src = 'https://www.youtube.com/embed/' + m[1];
			} else {
				throw 'invalid youtube link: ' + yt;
			}

			// set external links
			ytLinkElem.href = episode.external.youtube;
			igLinkElem.href = episode.external.instagram;
			ttLinkElem.href = episode.external.tiktok;

			if (isFirstEpisode(episode.num)) {
				prevEpisodeBtn.disabled = true;
				prevEpisodeBtn.setAttribute('title', 'This is the first episode :)');
			}
			if (isLastEpisode(episode.num)) {
				nextEpisodeBtn.disabled = true;
				nextEpisodeBtn.setAttribute('title', 'You have made it to the end! :D' );
			}
		</script>
	</body>
</html>
EOF
)
	fi

	if [ "$file" = void ]; then
		title='Awesome Void Linux | osowoso.org'
		h='	<li><a href="/">home</a></li>
					<li><a href="/episodes">episodes</a></li>
					<li><a href="/resources">resources</a></li>
					<li><a href="/projects">projects</a></li>
					<li><a href="/contributing">contributing</a></li>
					<li><a href="/void" class="active">void</a></li>
					<li class="right"><a href="/contact""active">contact</a></li>'
		top='<h1 class="title">&gt; void</h1>
			<!--<img
				src="https://secure.gravatar.com/avatar/6c7581ac69deeb96d3e9d0ee1e941af3?s=128" class="logo self-portrait" alt="ysap" width="128" />-->'
		body='	A collection of void and tools that Ive created that you all may find useful.
				<br><br>
				<ul>
					<li>- <a href="https://codeberg.org/mobinmob/xut">xut</a> - xtra user templates - Build and install packages for Void Linux, using templates from the abyss-packages unofficial repo</li>
				<br><br>

				<h2 class="title">Utilities</h2><br>
				Various utilities Ive created center around bash or programming in general.
				<br><br>
				<ul>
					<li>- <a href="https://github.com/bahamas10/bash-vardump">bash-vardump</a> - A <code class="highlight">vardump</code> function for bash</li>
					<li>- <a href="https://github.com/bahamas10/bash-stacktrace">bash-stacktrace</a> - A <code class="highlight">stacktrace</code> function for bash</li>
					<li>- <a href="https://github.com/bahamas10/sshp">sshp</a> - A parallel ssh executor in C</li>
				</ul>
				<br><br>

				<h2 class="title">Fun Extras</h2><br>
				Some less-useful but fun creations that Ive made and talked about in various videos.
				<br><br>
				<ul>
					<li>- <a href="https://bahamas10.github.io/ryb/">RYB Color Picker</a> - An RYB HTML Color Picker</li>
					<li>- <a href="https://xmas.osowoso.org">X-Mas Tree Animation</a> - Terminal animation made for Christmas in Bash</li>
					<li>- <a href="https://undercurrents.osowoso.org">Undercurrents</a> - A particle animation written in C using SDL2</li>
					<li>- <a href="https://nightfall.osowoso.org">Nightfall</a> - A music player TUI written in Bash</li>
				</ul>'
		footer='			<pre class="footer"><code>
source: <a class="alt" href="https://github.com/oSoWoSo/osowoso">github.com/oSoWoSo/osowoso</a>
&copy; zenobit - oSoWoSo <script>document.write(new Date().getFullYear())</script>
			</code></pre>
		</div>
	</body>
</html>'

	fi

	# shellcheck disable=SC2090
	export title h top body footer

	cat << EOF> "static/${file}.html"
<!doctype html>
<html>
	<head>
		<title>${title}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<link rel="icon" href="/static/favicon.jpg">

		<link rel="stylesheet" href="/static/style.css?v=3">
		<link rel="stylesheet" href="/static/ansi.css?v=2">

		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Fira+Mono:wght@400;500;700&display=swap" rel="stylesheet">
	</head>
	<body>
		<div id="container">
			<div id="top-nav">
				<ul>
				${h}
				</ul>
			</div>

			${top}
			<p class="content">
			${body}
			</p>
			${id}
${footer}
EOF

	unset title h top body footer
done
