#!/usr/bin/env bash
#shellcheck disable=SC2089
#
# Make episodes.html file
#
# Author: zenobit <zen@duck.com>
# Date: February 03, 2026
# License: MIT
#

echo "Creating episodes.html"

file=episodes

title='episodes | osowoso.org'

id='<br>

			<table id="episodes-table" class="shadow">
				<thead>
					<tr>
						<th>TITLE</th>
						<th>DESCRIPTION</th>
						<th>LINK</th>
					</tr>
				</thead>
				<tbody id="episodes-tbody">
				</tbody>
			</table>
'

h='	<li><a href="/">home</a></li>
					<li><a href="/projects">projects</a></li>
					<li><a href="/contributing">contributing</a></li>
					<li><a href="/void">void</a></li>
					<li><a href="/resources">resources</a></li>
					<li><a href="/episodes">episodes</a></li>
					<li class="right"><a href="/contact">contact</a></li>'

top='<h1 class="title">&gt; episodes</h1>
			<img src="/static/osowoso.png" class="logo hide-mobile" alt="osowoso" height="75" />'

body='	<span class="highlight">You Suck at
					Programming</span> is the series that
				kickstarted my content creation journey!<br><br>

				This series
				features 2-5 minute videos that cover cool
				Unix/Bash facts or gotchas, offering insights
				that are either useful or, at the very least,
					  interesting.
				<br>
				<br>
				There is also a compilation of the first 50
				episodes <a
				href="https://www.youtube.com/watch?v=KwRow9DdFJ0">available
				on YouTube</a>.
				<br>
				<br>
				<span class="highlight">$ curl</span> osowoso.org/episodes
				<br>'

footer=$(cat <<EOF
<pre class="footer"><code>
source: <a class="alt" href="https://github.com/oSoWoSo/osowoso">github.com/oSoWoSo/osowoso</a>
&copy; zenobit - oSoWoSo <script>document.write(new Date().getFullYear())</script>
			</code></pre>
		</div>
		<script src="/static/episodes.js"></script>
		<script>
			var tbody = document.getElementById('episodes-tbody');
			const episodeCount = EPISODES.episodes.length;

			EPISODES.episodes.forEach(function (episode) {
				let num = episode.num;

				let numFormatted = num.toString();
				for (let i = numFormatted.length; i < episodeCount.toString().length; i++) {
					numFormatted = '0' + numFormatted;
				}

				let tr = document.createElement('tr');
				let td, span;

				td = document.createElement('td');
				span = document.createElement('span');
				span.classList.add('number');
				span.innerHTML = numFormatted + '. ';
				td.appendChild(span);
				span = document.createElement('span');
				span.classList.add('name');
				span.textContent = episode.title;
				td.appendChild(span);
				td.classList.add('title');
				tr.appendChild(td);

				td = document.createElement('td');
				let i = 0;
				let s = '';
				episode.desc.split('').forEach(function (c) {
					switch (c) {
						case '&': c = '&amp;'; break;
						case '<': c = '&lt;'; break;
						case '>': c = '&gt;'; break;
						case '"': c = '&quot;'; break;
						case "'": c = '&#39;'; break;
						case '/': c = '&#47;'; break;
EOF
)

# shellcheck disable=SC2090
giscus=$(
	GISCUS_REPO="${GISCUS_REPO:-osowoso/osowoso}"
	GISCUS_REPO_ID="${GISCUS_REPO_ID:-R_kgDOPwu1wg}"
	GISCUS_CATEGORY_ID="${GISCUS_CATEGORY_ID:-DIC_kwDOPwu1ws4C1qTI}"
	GISCUS_MAPPING="${GISCUS_MAPPING:-pathname}"
	GISCUS_THEME="${GISCUS_THEME:-noborder_dark}"
	GISCUS_LANG="${GISCUS_LANG:-en}"
	cat << EOF
			<!-- GitHub Discussions Widget -->
			<div class="discussions-container" style="margin: 2em 0 1em 0; padding: 1em 0; border-top: 1px solid #444;">
				<script src="https://giscus.app/client.js"
					data-repo="$GISCUS_REPO"
					data-repo-id="$GISCUS_REPO_ID"
					data-category-id="$GISCUS_CATEGORY_ID"
					data-mapping="$GISCUS_MAPPING"
					data-strict="0"
					data-reactions-enabled="1"
					data-emit-metadata="0"
					data-input-position="bottom"
					data-theme="$GISCUS_THEME"
					data-lang="$GISCUS_LANG"
					data-loading="lazy"
					crossorigin="anonymous"
					async>
				</script>
			</div>
			<!-- End GitHub Discussions Widget -->
EOF
)

export title h top body giscus footer

cat << EOF> "static/${file}.html"
<!doctype html>
<html>
	<head>
		<title>${title}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<link rel="icon" href="/static/favicon.jpg">

		<link rel="stylesheet" href="/static/style.css?v=3">
		<link rel="stylesheet" href="/static/ansi.css?v=2">

		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Fira+Mono:wght@400;500;700&display=swap" rel="stylesheet">
	</head>
	<body>
		<div id="container">
			<div id="top-nav">
				<ul>
				${h}
				</ul>
			</div>

			${top}
			<p class="content">
			${body}
			</p>
			${id}
${giscus}
${footer}
EOF

unset title h top body footer
