#!/usr/bin/env bash
#
# Print the "about" message formatted how I like it - this output is intended to
# be piped into `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: January 30, 2026
# License: MIT
#
# Contributors: zenobit <zen@duck.com>

. ./theme || exit 1

readarray -t ABOUT << "EOF"
Don't buy a pig in a poke

Don't use proprietary Operating System or software

Use Open Source

Like Linux

Most used open source OS on planet Earth

Join us...


Our world is in our hands...


Anyone willing participate will be invited...

Only requirements is contributing to open source (no closed source allowed)

anyone can contribute their peace of puzzle

*** final goal
open Source World Society

Let's create our world open source
Because sharing is carring
And we care about our society

### This site will try to connect people, projects, organizations and ideas together
Our little open source crossroad site

# OPEN SOURCE RULES - from us for us

Purpose of this project is not create some rules for you, is it promote open source ideas everywhere is possible.

# Even in rule making.

If I am looking at state of politics I  cannot find any nice word for it.

I think it's time to stop voting for people and start voting for ideas. 

Simple idea:

# We can create our own rules!

![oSoWoSo](https://codeberg.org/avatars/4da60e696a206d2371e14e18c2fb15d6)

why?
- because "The pen is mightier than the sword"
- bacause Words are mightier then money.
- because We can.
- because We want real freedom.
- because Only all together we can make it best.

# sample

basic rules can be like:
1. Constitution cannot be violated.
2. Any kind of nature cannot be banned.
3. Land cannot by held.
4. Nature sources cannot by owned by comercial company or an individual.
5. Open sources must be promoted in every aspect of human life.
6. All software/format/hardware used by governments must be open source.
7. No closed source software/format/hardware may be used, promoted or enforced by government.
8. Government must fund developing of necessary open source software/format/hardware if not available.
9. Rules are created publicly in simple readable form using a selected versioning control system (eg. git) and commited after voting.
10. Anyone can contribute to the rules.
11. No rules cannot violate individual rights.


This project is (correct me if I'm wrong) one of the first attempt to create real open source rules that can be used to care for our countries and our world.


Can we stop talking about changes and start implementing it?

# Join REAL revolution!

Share links with anyone interested!

Link to join the oSoWoSo group on SimpleX chat:
[SimpleX chat](https://smp10.simplex.im/g#rg4Sryn9kAgLt5I4u9SdL4b34MQgR141e7y1LiOV7sI)

# Open Source Ecology
[OSE](https://www.opensourceecology.org/)

---
open Source World Society

[oSoWoSo](https://osowoso.org)

EOF

for line in "${ABOUT[@]}"; do
	echo "$COLOR1$line$RST"
done
