#!/usr/bin/env bash
#
# Make the body of the index page for osowoso.org
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: January 30, 2026
# License: MIT
#
# Contributors: zenobit <zen@duck.com>

m="$1"
file="${m%.md}"
title=$(echo "$file" | cut -d'/' -f2)

echo "Creating static/$title.html"

id='<div id="socials">
				<div id="socials">
					<a href="https://codeberg.org/oSoWoSo">Codeberg</a> |
					<a href="https://github.com/oSoWoSo">GitHub</a> |
					<a href="https://gitlab.com/osowoso">GitLab</a> |
					<a href="https://git.disroot.org/oSoWoSo">Disroot</a>
				</div>
					<!--
					<a href="https://osowoso.org/sh">SourceHut</a> |
					-->
					<!--
					<a href="https://osowoso.org/or">or</a> |
					-->
				<div id="git">
					<a href="https://smp10.simplex.im/g#rg4Sryn9kAgLt5I4u9SdL4b34MQgR141e7y1LiOV7sI">SimpleX</a> |
					<a href="https://youtube.com/@oSoWoSo.">YouTube</a> |
					<a href="https://patreon.com/oSoWoSo">Patreon</a>
					<!--
					<a href="https://osowoso.org/merch">Merch</a>
					-->
					<!--
					<a href=""></a>
					-->
				</div>
			</div>'

h='	<li><a href="/">home</a></li>
					<li><a href="/projects">projects</a></li>
					<li><a href="/contributing">contributing</a></li>
					<li><a href="/void">void</a></li>
					<li><a href="/resources">resources</a></li>
					<li><a href="/ysap">ysap</a></li>
					<li class="right"><a href="/contact">contact</a></li>'

top="	<h1 class=\"title\">&gt; ${title}</h1>"

body=$(pandoc "$1" -w html)

footer=$(cat << EOF
			<pre class="footer"><code>
source: <a class="alt" href="https://github.com/oSoWoSo/osowoso">github.com/oSoWoSo/osowoso</a>
&copy; zenobit - osowoso <script>document.write(new Date().getFullYear())</script>
			</code></pre>
		</div>
		<script src="/static/ysap.js"></script>
		<script>
			function isFirstEpisode(currentNum) {
				return currentNum === 1;
			}

			function isLastEpisode(currentNum) {
				return currentNum === EPISODES.episodes.length;
			}

			function getCurrentEpisodeNum() {
				// figure out what video we are based on the windows location
				const path = window.location.pathname
					.replace(/index\.html$/, '')
					.replace(/\/+$/, '');

				console.log('looking up %s', path);

				let m, num;
				if ((m = path.match(/^\/y\/([0-9]+)$/))) {
					num = m[1];
				} else {
					throw 'unrecoginzed url';
				}

				let episode = EPISODES.episodes[num - 1];
				if (!episode) {
					throw 'non existent episode';
				}

				return +num;
			}

			function goToNextEpisode() {
				let nextNum = getCurrentEpisodeNum() + 1;
				let nextEpisode = EPISODES.episodes[nextNum - 1];
				if (nextEpisode) {
					globalThis.location.href = '/y/' + nextNum;
				}
			}

			function goToPrevEpisode() {
				let prevNum = getCurrentEpisodeNum() - 1;
				let prevEpisode = EPISODES.episodes[prevNum - 1];
				if (prevEpisode) {
					globalThis.location.href = '/y/' + prevNum;
				}
			}

			const titleElem = document.getElementById('video-title');
			const descriptionElem = document.getElementById('video-description');
			const ytVideoElem = document.getElementById('video-yt-frame');

			const ytLinkElem = document.getElementById('video-youtube-link');
			const igLinkElem = document.getElementById('video-instagram-link');
			const ttLinkElem = document.getElementById('video-tiktok-link');

			const prevEpisodeBtn = document.getElementById('prev-episode-btn');
			const nextEpisodeBtn = document.getElementById('next-episode-btn');

			const num = getCurrentEpisodeNum();
			const episode = EPISODES.episodes[num - 1];

			// set title and description
			titleElem.textContent = num + '. ' + episode.title;
			descriptionElem.textContent = episode.desc;
			document.title = episode.title + ' | osowoso.org';

			// set youtube iframe
			let yt = episode.external.youtube;
			// Trying to fix v->y issues
			//if ((m = yt.match(/v=(.*)$/))) {
			//
			if ((m = yt.match(/y=(.*)$/))) {
				ytVideoElem.src = 'https://www.youtube.com/embed/' + m[1];
			} else {
				throw 'invalid youtube link: ' + yt;
			}

			// set external links
			ytLinkElem.href = episode.external.youtube;
			igLinkElem.href = episode.external.instagram;
			ttLinkElem.href = episode.external.tiktok;

			if (isFirstEpisode(episode.num)) {
				prevEpisodeBtn.disabled = true;
				prevEpisodeBtn.setAttribute('title', 'This is the first episode :)');
			}
			if (isLastEpisode(episode.num)) {
				nextEpisodeBtn.disabled = true;
				nextEpisodeBtn.setAttribute('title', 'You have made it to the end! :D' );
			}
		</script>
	</body>
</html>
EOF
)

# shellcheck disable=SC2090
giscus=$(
		GISCUS_REPO="${GISCUS_REPO:-osowoso/osowoso}"
		GISCUS_REPO_ID="${GISCUS_REPO_ID:-R_kgDOPwu1wg}"
		GISCUS_CATEGORY_ID="${GISCUS_CATEGORY_ID:-DIC_kwDOPwu1ws4C1qTI}"
		GISCUS_MAPPING="${GISCUS_MAPPING:-pathname}"
		GISCUS_THEME="${GISCUS_THEME:-noborder_dark}"
		GISCUS_LANG="${GISCUS_LANG:-en}"
		cat << EOF
			<!-- GitHub Discussions Widget -->
			<div class="discussions-container" style="margin: 2em 0 1em 0; padding: 1em 0; border-top: 1px solid #444;">
				<script src="https://giscus.app/client.js"
					data-repo="$GISCUS_REPO"
					data-repo-id="$GISCUS_REPO_ID"
					data-category-id="$GISCUS_CATEGORY_ID"
					data-mapping="$GISCUS_MAPPING"
					data-strict="0"
					data-reactions-enabled="1"
					data-emit-metadata="0"
					data-input-position="bottom"
					data-theme="$GISCUS_THEME"
					data-lang="$GISCUS_LANG"
					data-loading="lazy"
					crossorigin="anonymous"
					async>
				</script>
			</div>
			<!-- End GitHub Discussions Widget -->
EOF
)

export title h top body giscus footer
cat << EOF> "_site/${file}.html"
<!doctype html>
<html>
	<head>
		<title>${title}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<link rel="icon" href="/static/favicon.jpg">

		<link rel="stylesheet" href="/static/style.css?v=4">
		<link rel="stylesheet" href="/static/ansi.css?v=2">

		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Fira+Mono:wght@400;500;700&display=swap" rel="stylesheet">
	</head>
	<body>
		<div id="container">
			<div id="top-nav">
				<ul>
				${m}
				</ul>
			</div>

			${top}
			<p class="content">
			${body}
			</p>
			${id}
${giscus}
${footer}
EOF

unset title h top body footer
