#!/usr/bin/env bash
#shellcheck disable=SC2089
#
# Make projects.html file
#
# Author: zenobit <zen@duck.com>
# Date: February 03, 2026
# License: MIT
#

echo "projects.html"

file=projects

title='projects | osowoso.org'

id='<div id="socials">
				<div id="socials">
					<a href="https://codeberg.org/oSoWoSo">Codeberg</a> |
					<a href="https://github.com/oSoWoSo">GitHub</a> |
					<a href="https://gitlab.com/osowoso">GitLab</a> |
					<a href="https://git.disroot.org/oSoWoSo">Disroot</a>
				</div>
					<!--
					<a href="https://osowoso.org/sh">SourceHut</a> |
					-->
					<!--
					<a href="https://osowoso.org/or">or</a> |
					-->
				<div id="git">
					<a href="https://smp10.simplex.im/g#rg4Sryn9kAgLt5I4u9SdL4b34MQgR141e7y1LiOV7sI">SimpleX</a> |
					<a href="https://youtube.com/@oSoWoSo.">YouTube</a> |
					<a href="https://patreon.com/oSoWoSo">Patreon</a>
					<!--
					<a href="https://osowoso.org/merch">Merch</a>
					-->
					<!--
					<a href=""></a>
					-->
				</div>
			</div>'

h='	<li><a href="/">home</a></li>
					<li><a href="/projects" class="active">projects</a></li>
					<li><a href="/contributing">contributing</a></li>
					<li><a href="/void">void</a></li>
					<li><a href="/resources">resources</a></li>
					<li><a href="/ysap">ysap</a></li>
					<li class="right"><a href="/contact""active">contact</a></li>'

top='<h1 class="title">&gt; projects</h1>
			<!--<img
				src="https://secure.gravatar.com/avatar/abfe8049a00a6dadca4c4c7b5bf19ed833d33393e42ed9501979201488c12494?s=128" class="logo self-portrait" alt="ysap" width="128" />-->'

body='	A collection of projects and tools that you may find useful.
				<br><br>
				<ul>
				<li>- <a href="https://github.com/zen0bit/awesome-stars">awesome-stars</a> - My Awesome List </li>
				<li>- <a href="https://github.com/oSoWoSo/awesome-void-linux">awesome-void-linux</a> - List of awesome applications, software, tools and other materials for Void Linux</li>
				<li>- <a href="https://github.com/oSoWoSo/cayman-vb-dark">cayman-vb-dark</a> - Dark mode adaptation of Cayman jekyll theme</li>
				<li>- <a href="https://osowoso.org/dh">DistroHopper</a> - Quickly download, create and run VM of any#TODO operating system</li>
				<li>- <a href="https://github.com/oSoWoSo/distro-svg">distro-svg</a> - Collection of distro icons in svg format</li>
				<li>- <a href="https://github.com/oSoWoSo/dotbot-xi">dotbot-xi</a> - Dotbot xi plugin (Use xi from xtools) </li>
				<li>- <a href="https://osowoso.org/gumak/">gumak</a> - Gumák and other usefull TUIs </li>
				<li>- <a href="https://github.com/oSoWoSo/passthrough_helper_void">passthrough_helper_void</a> - GPU passthrough helper</li>
				<li>- <a href="https://github.com/oSoWoSo/piu">piu</a> - Cross platform package manager wrapper</li>
				<li>- <a href="https://github.com/oSoWoSo/quickemu-font-and-logos">quickemu-font-and-logos</a> - Icon font containing logos of popular Operating Systems</li>
				<li>- <a href="https://github.com/oSoWoSo/SimpleX-Themes">SimpleX-Themes</a> - Repository for SimpleX Chat themes</li>
				<li>- <a href="https://github.com/oSoWoSo/vbm">vbm</a> - XBPS package management helper for VoidLinux</li>
				<li>- <a href="https://wall.osowoso.org">void-artwork</a> - Collection of artworks for Void linux</li>
				<li>- <a href="https://github.com/oSoWoSo/void-helper">void-helper</a> - Configuration script for Void Linux that guides you through several steps with questions</li>
				<li>- <a href="https://github.com/oSoWoSo/Void-In-Termux">Void-In-Termux</a> - This intends to allow a proot from Termux to Void Linux rootfs</li>
				<li>- <a href="https://github.com/oSoWoSo/VUR">VUR</a> - Void User Repository templates collection</li>
				<li>- <a href="https://github.com/oSoWoSo/vut">vut</a> - Void Linux Ultimate Tool: mainly for ease of xbps-src use</li>
				<!--
				<li>- <a href=""></a> - </li>
				-->
				</ul>
				<br><br>'

footer='			<pre class="footer"><code>
source: <a class="alt" href="https://github.com/oSoWoSo/osowoso">github.com/oSoWoSo/osowoso</a>
&copy; zenobit - oSoWoSo <script>document.write(new Date().getFullYear())</script>
			</code></pre>
		</div>
	</body>
</html>'

# shellcheck disable=SC2090
giscus=$(
	GISCUS_REPO="${GISCUS_REPO:-osowoso/osowoso}"
	GISCUS_REPO_ID="${GISCUS_REPO_ID:-R_kgDOPwu1wg}"
	GISCUS_CATEGORY_ID="${GISCUS_CATEGORY_ID:-DIC_kwDOPwu1ws4C1qTI}"
	GISCUS_MAPPING="${GISCUS_MAPPING:-pathname}"
	GISCUS_THEME="${GISCUS_THEME:-noborder_dark}"
	GISCUS_LANG="${GISCUS_LANG:-en}"
	cat << EOF
			<!-- GitHub Discussions Widget -->
			<div class="discussions-container" style="margin: 2em 0 1em 0; padding: 1em 0; border-top: 1px solid #444;">
				<script src="https://giscus.app/client.js"
					data-repo="$GISCUS_REPO"
					data-repo-id="$GISCUS_REPO_ID"
					data-category-id="$GISCUS_CATEGORY_ID"
					data-mapping="$GISCUS_MAPPING"
					data-strict="0"
					data-reactions-enabled="1"
					data-emit-metadata="0"
					data-input-position="bottom"
					data-theme="$GISCUS_THEME"
					data-lang="$GISCUS_LANG"
					data-loading="lazy"
					crossorigin="anonymous"
					async>
				</script>
			</div>
			<!-- End GitHub Discussions Widget -->
EOF
)

export title h top body giscus footer

cat << EOF> "_site/${file}.html"
<!doctype html>
<html>
	<head>
		<title>${title}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<link rel="icon" href="/static/favicon.jpg">

		<link rel="stylesheet" href="/static/style.css?v=4">
		<link rel="stylesheet" href="/static/ansi.css?v=2">

		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Fira+Mono:wght@400;500;700&display=swap" rel="stylesheet">
	</head>
	<body>
		<div id="container">
			<div id="top-nav">
				<ul>
				${h}
				</ul>
			</div>

			${top}
			<p class="content">
			${body}
			</p>
			${id}
${giscus}
${footer}
EOF

unset title h top body footer
