#!/usr/bin/env bash
#
# My personal color theme for the website - loosely based on a dark solarized
# theme
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: January 30, 2026
# License: MIT
#
# Contributors: zenobit <zen@duck.com>

COLOR1=$'\x1b[38;5;87m'   # cyan
COLOR2=$'\x1b[38;5;211m'  # magenta
COLOR3=$'\x1b[38;5;120m'  # green
COLOR4=$'\x1b[38;5;241m'  # dim
COLOR5=$'\x1b[38;5;223m'  # off-white (text)
RST=$'\x1b[0m'
